class parallel_command:

    def __init__(self, binary='/usr/bin/hostname', args=[]):
        self.binary = binary
        self.args = args

    def expand(self):
        text = '\n# GEPY Parallel command.\n'
        text = text + 'gerun' + ' ' + self.binary
        for a in self.args:
            text = text + ' ' + a
        text = text + '\n'
        return text

class serial_command:

    def __init__(self, binary='/usr/bin/hostname', args=[]):
        self.binary = binary
        self.args = args

    def expand(self):
        text = '\n# GEPY serial command.\n'
        text = text + self.binary
        for a in self.args:
            text = text + ' ' + args
        text = text + '\n'
        return text

class user_script:

    def __init__(self, script=''):
        self.script = script   

    def expand(self):
        text = '\n# User supplied shell code.\n'
        text = text + self.script + '\n'
        text = text + '# End user supplied shell code.\n'
        return text

class job:

    def __init__(self, name='gepy_job', memory=1024, length=60, location='.'):
        import math
        self.name = name
        self.resources = {}
        self.add_resource('mem',memory)
        hrs = math.floor(length/60)
        mins = length%60
        self.add_resource('h_rt',str(hrs) + ':' + str(mins) + ':00')
        self.location = location
        self.modules = []
        self.workload = []


    def add_resource(self,name,value):
        self.resources[name] = value

    def get_job_script(self):
        import math
        script = '#!/bin/bash -l\n'
        script = script + '# Job script generated by GEPY (https://github.com/owainkenwayucl/gepy)\n'
        script = script + '#$ -N ' + self.name + '\n'
        for a in self.resources.keys():
            script = script + '#$ -l ' + a + '=' + self.resources[a] + '\n'

        if (self.location == '.'):
            script = script + '#$ -cwd\n'
        else:
            script = script + '#$ -wd ' + self.location + '\n'

        for a in self.modules:
            script = script + 'module load ' + a + '\n'

        for a in self.workload:
            script = script + a.expand() + '\n'

        return script

        

